openapi: 3.0.0
info:
  title: BeverageService API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /beverages:
    get:
      summary: Get all bottles
      parameters:
        - in: query
          name: minPrice
          schema: { type: number }
        - in: query
          name: maxPrice
          schema: { type: number }
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 10 }
      responses:
        200:
          description: List of bottles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bottle'

components:
  schemas:
    Bottle:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        price: { type: number }
        supplier: { type: string }
